// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.3
// source: app/notification/rpc/pb/notification.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 业务侧投递通知事件（好友申请、点赞等）
type PushEventReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType   string   `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`       // 必填：friend_request/moment_like/moment_comment/group_join/...
	Category    string   `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`                          // 必填：social/moment/group/system
	FromUserId  string   `protobuf:"bytes,3,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`  // 触发方
	TargetId    string   `protobuf:"bytes,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`          // 目标对象ID（如动态ID、群ID、用户ID）
	TargetType  string   `protobuf:"bytes,5,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`    // 目标类型：moment/group/user/other
	PayloadJson string   `protobuf:"bytes,6,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"` // 扩展数据JSON（前端可渲染）
	ToUserIds   []string `protobuf:"bytes,7,rep,name=to_user_ids,json=toUserIds,proto3" json:"to_user_ids,omitempty"`     // 接收人列表
	DedupHash   string   `protobuf:"bytes,8,opt,name=dedup_hash,json=dedupHash,proto3" json:"dedup_hash,omitempty"`       // 可选，幂等/合并用
}

func (x *PushEventReq) Reset() {
	*x = PushEventReq{}
	mi := &file_app_notification_rpc_pb_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushEventReq) ProtoMessage() {}

func (x *PushEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_notification_rpc_pb_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushEventReq.ProtoReflect.Descriptor instead.
func (*PushEventReq) Descriptor() ([]byte, []int) {
	return file_app_notification_rpc_pb_notification_proto_rawDescGZIP(), []int{0}
}

func (x *PushEventReq) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PushEventReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *PushEventReq) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *PushEventReq) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *PushEventReq) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *PushEventReq) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *PushEventReq) GetToUserIds() []string {
	if x != nil {
		return x.ToUserIds
	}
	return nil
}

func (x *PushEventReq) GetDedupHash() string {
	if x != nil {
		return x.DedupHash
	}
	return ""
}

type PushEventRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // 生成的事件ID
	Version int64  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`               // 事件版本（全局序列）
}

func (x *PushEventRes) Reset() {
	*x = PushEventRes{}
	mi := &file_app_notification_rpc_pb_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushEventRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushEventRes) ProtoMessage() {}

func (x *PushEventRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_notification_rpc_pb_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushEventRes.ProtoReflect.Descriptor instead.
func (*PushEventRes) Descriptor() ([]byte, []int) {
	return file_app_notification_rpc_pb_notification_proto_rawDescGZIP(), []int{1}
}

func (x *PushEventRes) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PushEventRes) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_app_notification_rpc_pb_notification_proto protoreflect.FileDescriptor

var file_app_notification_rpc_pb_notification_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x61, 0x70, 0x70, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x22, 0x8b, 0x02, 0x0a, 0x0c, 0x50, 0x75, 0x73, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x0c,
	0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x4a, 0x73, 0x6f, 0x6e, 0x12,
	0x1e, 0x0a, 0x0b, 0x74, 0x6f, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x07,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x12,
	0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x64, 0x75, 0x70, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x64, 0x75, 0x70, 0x48, 0x61, 0x73, 0x68, 0x22, 0x43,
	0x0a, 0x0c, 0x50, 0x75, 0x73, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x12, 0x19,
	0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x32, 0x3f, 0x0a, 0x0c, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x2f, 0x0a, 0x09, 0x50, 0x75, 0x73, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_notification_rpc_pb_notification_proto_rawDescOnce sync.Once
	file_app_notification_rpc_pb_notification_proto_rawDescData = file_app_notification_rpc_pb_notification_proto_rawDesc
)

func file_app_notification_rpc_pb_notification_proto_rawDescGZIP() []byte {
	file_app_notification_rpc_pb_notification_proto_rawDescOnce.Do(func() {
		file_app_notification_rpc_pb_notification_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_notification_rpc_pb_notification_proto_rawDescData)
	})
	return file_app_notification_rpc_pb_notification_proto_rawDescData
}

var file_app_notification_rpc_pb_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_notification_rpc_pb_notification_proto_goTypes = []any{
	(*PushEventReq)(nil), // 0: pb.PushEventReq
	(*PushEventRes)(nil), // 1: pb.PushEventRes
}
var file_app_notification_rpc_pb_notification_proto_depIdxs = []int32{
	0, // 0: pb.notification.PushEvent:input_type -> pb.PushEventReq
	1, // 1: pb.notification.PushEvent:output_type -> pb.PushEventRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_notification_rpc_pb_notification_proto_init() }
func file_app_notification_rpc_pb_notification_proto_init() {
	if File_app_notification_rpc_pb_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_notification_rpc_pb_notification_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_notification_rpc_pb_notification_proto_goTypes,
		DependencyIndexes: file_app_notification_rpc_pb_notification_proto_depIdxs,
		MessageInfos:      file_app_notification_rpc_pb_notification_proto_msgTypes,
	}.Build()
	File_app_notification_rpc_pb_notification_proto = out.File
	file_app_notification_rpc_pb_notification_proto_rawDesc = nil
	file_app_notification_rpc_pb_notification_proto_goTypes = nil
	file_app_notification_rpc_pb_notification_proto_depIdxs = nil
}
