// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: usercenter.proto

package usercenter

import (
	"context"

	"beaver-server/app/usercenter/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	RegisterUserReq  = pb.RegisterUserReq
	RegisterUserResp = pb.RegisterUserResp

	Usercenter interface {
		// 注册用户
		RegisterUser(ctx context.Context, in *RegisterUserReq, opts ...grpc.CallOption) (*RegisterUserResp, error)
	}

	defaultUsercenter struct {
		cli zrpc.Client
	}
)

func NewUsercenter(cli zrpc.Client) Usercenter {
	return &defaultUsercenter{
		cli: cli,
	}
}

// 注册用户
func (m *defaultUsercenter) RegisterUser(ctx context.Context, in *RegisterUserReq, opts ...grpc.CallOption) (*RegisterUserResp, error) {
	client := pb.NewUsercenterClient(m.cli.Conn())
	return client.RegisterUser(ctx, in, opts...)
}
