// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GetEmailVerificationCodeRequest struct {
	Email string `json:"email"`
	Type  string `json:"type"`
}

type GetEmailVerificationCodeResponse struct {
	Message string `json:"message"`
}

type RegisterUserRequest struct {
	Email            string `json:"email, optional"`
	Phone            string `json:"phone, optional"`
	Password         string `json:"password"`
	VerificationCode string `json:"verificationCode"`
	Type             string `json:"type"`
}

type RegisterUserResponse struct {
	Message string `json:"message"`
}
