// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GetEmailVerificationCodeRequest struct {
	Email string `json:"email"`
	Type  string `json:"type"`
}

type GetEmailVerificationCodeResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type LoginUserRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginUserResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Token   string `json:"token"`
}

type RegisterUserRequest struct {
	Email            string `json:"email, optional"`
	Phone            string `json:"phone, optional"`
	Password         string `json:"password"`
	VerificationCode string `json:"verificationCode"`
	Type             string `json:"type"`
}

type RegisterUserResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}
