// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type FriendInfo struct {
	UserID         string `json:"userId"`         // 用户ID
	NickName       string `json:"nickName"`       // 用户昵称
	Avatar         string `json:"avatar"`         // 用户头像文件名
	Abstract       string `json:"abstract"`       // 用户签名
	Notice         string `json:"notice"`         // 好友备注
	IsFriend       bool   `json:"isFriend"`       // 是否为好友关系
	ConversationID string `json:"conversationId"` // 会话ID
	Email          string `json:"email"`          // 用户邮箱
	Source         string `json:"source"`         // 好友关系来源：email/qrcode
}

type FriendInfoReq struct {
	UserID   string `form:"userId"`   // 当前用户ID
	FriendID string `form:"friendId"` // 好友用户ID
}

type FriendInfoRes struct {
	Code    int        `json:"code"`    // 状态码
	Message string     `json:"message"` // 状态描述
	Result  FriendInfo `json:"result"`  // 好友详细信息
}

type SearchReq struct {
	Email string `form:"email"`
}

type SearchRes struct {
	Code   int  `json:"code"`   // 状态码
	Result User `json:"result"` // 搜索结果
}

type User struct {
	Name     string `json:"name"`
	NickName string `json:"nickName"`
	Gender   string `json:"gender"`
	Avatar   string `json:"avatar"`
	Email    string `json:"email"`
}
