// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"beaver-server/app/friend/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取好友详细信息
				Method:  http.MethodGet,
				Path:    "/api/friend/friend_info",
				Handler: friendInfoHandler(serverCtx),
			},
			{
				// 通过邮箱搜索用户
				Method:  http.MethodGet,
				Path:    "/api/friend/search",
				Handler: searchHandler(serverCtx),
			},
		},
	)
}
