// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: notification.proto

package server

import (
	"context"

	"beaver-server/app/notification/rpc/internal/logic"
	"beaver-server/app/notification/rpc/internal/svc"
	"beaver-server/app/notification/rpc/pb"
)

type NotificationServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedNotificationServer
}

func NewNotificationServer(svcCtx *svc.ServiceContext) *NotificationServer {
	return &NotificationServer{
		svcCtx: svcCtx,
	}
}

func (s *NotificationServer) PushEvent(ctx context.Context, in *pb.PushEventReq) (*pb.PushEventRes, error) {
	l := logic.NewPushEventLogic(ctx, s.svcCtx)
	return l.PushEvent(in)
}
