// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: usercenter.proto

package server

import (
	"context"

	"beaver-server/app/usercenter/rpc/internal/logic"
	"beaver-server/app/usercenter/rpc/internal/svc"
	"beaver-server/app/usercenter/rpc/pb"
)

type UsercenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUsercenterServer
}

func NewUsercenterServer(svcCtx *svc.ServiceContext) *UsercenterServer {
	return &UsercenterServer{
		svcCtx: svcCtx,
	}
}

// 注册用户
func (s *UsercenterServer) RegisterUser(ctx context.Context, in *pb.RegisterUserReq) (*pb.RegisterUserResp, error) {
	l := logic.NewRegisterUserLogic(ctx, s.svcCtx)
	return l.RegisterUser(in)
}

// 用户登录
func (s *UsercenterServer) LoginUser(ctx context.Context, in *pb.LoginUserReq) (*pb.LoginUserResp, error) {
	l := logic.NewLoginUserLogic(ctx, s.svcCtx)
	return l.LoginUser(in)
}
