// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"beaver-server/app/usercenter/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取邮箱验证码
				Method:  http.MethodPost,
				Path:    "/api/auth/emailcode",
				Handler: getEmailVerificationCodeHandler(serverCtx),
			},
			{
				// 注册用户
				Method:  http.MethodPost,
				Path:    "/api/auth/register",
				Handler: registerUserHandler(serverCtx),
			},
		},
	)
}
