// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: notification.proto

package notification

import (
	"context"

	"beaver-server/app/notification/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PushEventReq = pb.PushEventReq
	PushEventRes = pb.PushEventRes

	Notification interface {
		PushEvent(ctx context.Context, in *PushEventReq, opts ...grpc.CallOption) (*PushEventRes, error)
	}

	defaultNotification struct {
		cli zrpc.Client
	}
)

func NewNotification(cli zrpc.Client) Notification {
	return &defaultNotification{
		cli: cli,
	}
}

func (m *defaultNotification) PushEvent(ctx context.Context, in *PushEventReq, opts ...grpc.CallOption) (*PushEventRes, error) {
	client := pb.NewNotificationClient(m.cli.Conn())
	return client.PushEvent(ctx, in, opts...)
}
