// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	notificationInboxFieldNames          = builder.RawFieldNames(&NotificationInbox{})
	notificationInboxRows                = strings.Join(notificationInboxFieldNames, ",")
	notificationInboxRowsExpectAutoSet   = strings.Join(stringx.Remove(notificationInboxFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	notificationInboxRowsWithPlaceHolder = strings.Join(stringx.Remove(notificationInboxFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheNotificationInboxIdPrefix = "cache:notificationInbox:id:"
)

type (
	notificationInboxModel interface {
		Insert(ctx context.Context, data *NotificationInbox) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*NotificationInbox, error)
		Update(ctx context.Context, data *NotificationInbox) error
		Delete(ctx context.Context, id int64) error
	}

	defaultNotificationInboxModel struct {
		sqlc.CachedConn
		table string
	}

	NotificationInbox struct {
		Id        int64        `db:"id"`
		UserId    string       `db:"userId"` // 收件人
		EventId   string       `db:"eventId"`
		EventType string       `db:"eventType"`
		Category  string       `db:"category"`
		Version   int64        `db:"version"`
		IsRead    int64        `db:"isRead"`
		ReadAt    sql.NullTime `db:"readAt"`
		Status    int64        `db:"status"`
		IsDeleted int64        `db:"isDeleted"`
		Silent    int64        `db:"silent"`
		CreatedAt time.Time    `db:"created_at"`
		UpdatedAt time.Time    `db:"updated_at"`
		DeletedAt sql.NullTime `db:"deleted_at"`
	}
)

func newNotificationInboxModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultNotificationInboxModel {
	return &defaultNotificationInboxModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`notificationInbox`",
	}
}

func (m *defaultNotificationInboxModel) Delete(ctx context.Context, id int64) error {
	notificationInboxIdKey := fmt.Sprintf("%s%v", cacheNotificationInboxIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, notificationInboxIdKey)
	return err
}

func (m *defaultNotificationInboxModel) FindOne(ctx context.Context, id int64) (*NotificationInbox, error) {
	notificationInboxIdKey := fmt.Sprintf("%s%v", cacheNotificationInboxIdPrefix, id)
	var resp NotificationInbox
	err := m.QueryRowCtx(ctx, &resp, notificationInboxIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", notificationInboxRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNotificationInboxModel) Insert(ctx context.Context, data *NotificationInbox) (sql.Result, error) {
	notificationInboxIdKey := fmt.Sprintf("%s%v", cacheNotificationInboxIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, notificationInboxRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.EventId, data.EventType, data.Category, data.Version, data.IsRead, data.ReadAt, data.Status, data.IsDeleted, data.Silent, data.DeletedAt)
	}, notificationInboxIdKey)
	return ret, err
}

func (m *defaultNotificationInboxModel) Update(ctx context.Context, data *NotificationInbox) error {
	notificationInboxIdKey := fmt.Sprintf("%s%v", cacheNotificationInboxIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, notificationInboxRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.EventId, data.EventType, data.Category, data.Version, data.IsRead, data.ReadAt, data.Status, data.IsDeleted, data.Silent, data.DeletedAt, data.Id)
	}, notificationInboxIdKey)
	return err
}

func (m *defaultNotificationInboxModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheNotificationInboxIdPrefix, primary)
}

func (m *defaultNotificationInboxModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", notificationInboxRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultNotificationInboxModel) tableName() string {
	return m.table
}
