// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	notificationEventFieldNames          = builder.RawFieldNames(&NotificationEvent{})
	notificationEventRows                = strings.Join(notificationEventFieldNames, ",")
	notificationEventRowsExpectAutoSet   = strings.Join(stringx.Remove(notificationEventFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	notificationEventRowsWithPlaceHolder = strings.Join(stringx.Remove(notificationEventFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheNotificationEventIdPrefix      = "cache:notificationEvent:id:"
	cacheNotificationEventEventIdPrefix = "cache:notificationEvent:eventId:"
)

type (
	notificationEventModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *NotificationEvent) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*NotificationEvent, error)
		FindOneByEventId(ctx context.Context, eventId string) (*NotificationEvent, error)
		Update(ctx context.Context, data *NotificationEvent) error
		Delete(ctx context.Context, id int64) error
		Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error
	}

	defaultNotificationEventModel struct {
		sqlc.CachedConn
		table string
	}

	NotificationEvent struct {
		Id         int64          `db:"id"`
		EventId    string         `db:"eventId"`    // The event id
		EventType  string         `db:"eventType"`  // The event type
		Category   string         `db:"category"`   // The event category
		Version    int64          `db:"version"`    // The event version
		FromUserId string         `db:"fromUserId"` // The from user id
		TargetId   string         `db:"targetId"`   // The target user id
		TargetType string         `db:"targetType"` // The target user type
		Payload    sql.NullString `db:"payload"`    // The event payload
		Priority   int64          `db:"priority"`   // The event priority
		Status     int64          `db:"status"`     // The event status
		DedupHash  sql.NullString `db:"dedupHash"`  // The event dedup hash
		CreateAt   time.Time      `db:"create_at"`
		UpdateAt   time.Time      `db:"update_at"`
	}
)

func newNotificationEventModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultNotificationEventModel {
	return &defaultNotificationEventModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`notificationEvent`",
	}
}

func (m *defaultNotificationEventModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	notificationEventEventIdKey := fmt.Sprintf("%s%v", cacheNotificationEventEventIdPrefix, data.EventId)
	notificationEventIdKey := fmt.Sprintf("%s%v", cacheNotificationEventIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, notificationEventEventIdKey, notificationEventIdKey)
	return err
}

func (m *defaultNotificationEventModel) FindOne(ctx context.Context, id int64) (*NotificationEvent, error) {
	notificationEventIdKey := fmt.Sprintf("%s%v", cacheNotificationEventIdPrefix, id)
	var resp NotificationEvent
	err := m.QueryRowCtx(ctx, &resp, notificationEventIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", notificationEventRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNotificationEventModel) FindOneByEventId(ctx context.Context, eventId string) (*NotificationEvent, error) {
	notificationEventEventIdKey := fmt.Sprintf("%s%v", cacheNotificationEventEventIdPrefix, eventId)
	var resp NotificationEvent
	err := m.QueryRowIndexCtx(ctx, &resp, notificationEventEventIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `eventId` = ? limit 1", notificationEventRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, eventId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNotificationEventModel) Insert(ctx context.Context, session sqlx.Session, data *NotificationEvent) (sql.Result, error) {
	notificationEventEventIdKey := fmt.Sprintf("%s%v", cacheNotificationEventEventIdPrefix, data.EventId)
	notificationEventIdKey := fmt.Sprintf("%s%v", cacheNotificationEventIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, notificationEventRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.EventId, data.EventType, data.Category, data.Version, data.FromUserId, data.TargetId, data.TargetType, data.Payload, data.Priority, data.Status, data.DedupHash)
	}, notificationEventEventIdKey, notificationEventIdKey)
	return ret, err
}

func (m *defaultNotificationEventModel) Update(ctx context.Context, newData *NotificationEvent) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	notificationEventEventIdKey := fmt.Sprintf("%s%v", cacheNotificationEventEventIdPrefix, data.EventId)
	notificationEventIdKey := fmt.Sprintf("%s%v", cacheNotificationEventIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, notificationEventRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.EventId, newData.EventType, newData.Category, newData.Version, newData.FromUserId, newData.TargetId, newData.TargetType, newData.Payload, newData.Priority, newData.Status, newData.DedupHash, newData.Id)
	}, notificationEventEventIdKey, notificationEventIdKey)
	return err
}

func (m *defaultNotificationEventModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultNotificationEventModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheNotificationEventIdPrefix, primary)
}

func (m *defaultNotificationEventModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", notificationEventRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultNotificationEventModel) tableName() string {
	return m.table
}
