// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.3
// source: app/friend/rpc/pb/friend.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsFriendReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId1 string `protobuf:"bytes,1,opt,name=userId1,proto3" json:"userId1,omitempty"`
	UserId2 string `protobuf:"bytes,2,opt,name=userId2,proto3" json:"userId2,omitempty"`
}

func (x *IsFriendReq) Reset() {
	*x = IsFriendReq{}
	mi := &file_app_friend_rpc_pb_friend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFriendReq) ProtoMessage() {}

func (x *IsFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_friend_rpc_pb_friend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFriendReq.ProtoReflect.Descriptor instead.
func (*IsFriendReq) Descriptor() ([]byte, []int) {
	return file_app_friend_rpc_pb_friend_proto_rawDescGZIP(), []int{0}
}

func (x *IsFriendReq) GetUserId1() string {
	if x != nil {
		return x.UserId1
	}
	return ""
}

func (x *IsFriendReq) GetUserId2() string {
	if x != nil {
		return x.UserId2
	}
	return ""
}

type IsFriendRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsFriend bool `protobuf:"varint,1,opt,name=isFriend,proto3" json:"isFriend,omitempty"`
}

func (x *IsFriendRes) Reset() {
	*x = IsFriendRes{}
	mi := &file_app_friend_rpc_pb_friend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFriendRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFriendRes) ProtoMessage() {}

func (x *IsFriendRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_friend_rpc_pb_friend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFriendRes.ProtoReflect.Descriptor instead.
func (*IsFriendRes) Descriptor() ([]byte, []int) {
	return file_app_friend_rpc_pb_friend_proto_rawDescGZIP(), []int{1}
}

func (x *IsFriendRes) GetIsFriend() bool {
	if x != nil {
		return x.IsFriend
	}
	return false
}

var File_app_friend_rpc_pb_friend_proto protoreflect.FileDescriptor

var file_app_friend_rpc_pb_friend_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x70, 0x70, 0x2f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2f, 0x72, 0x70, 0x63,
	0x2f, 0x70, 0x62, 0x2f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x41, 0x0a, 0x0b, 0x69, 0x73, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x31, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x31, 0x12, 0x18, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x32, 0x22, 0x29, 0x0a, 0x0b, 0x69, 0x73, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x32, 0x36, 0x0a, 0x06, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x2c, 0x0a, 0x08,
	0x69, 0x73, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x69, 0x73,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x69,
	0x73, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_friend_rpc_pb_friend_proto_rawDescOnce sync.Once
	file_app_friend_rpc_pb_friend_proto_rawDescData = file_app_friend_rpc_pb_friend_proto_rawDesc
)

func file_app_friend_rpc_pb_friend_proto_rawDescGZIP() []byte {
	file_app_friend_rpc_pb_friend_proto_rawDescOnce.Do(func() {
		file_app_friend_rpc_pb_friend_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_friend_rpc_pb_friend_proto_rawDescData)
	})
	return file_app_friend_rpc_pb_friend_proto_rawDescData
}

var file_app_friend_rpc_pb_friend_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_friend_rpc_pb_friend_proto_goTypes = []any{
	(*IsFriendReq)(nil), // 0: pb.isFriendReq
	(*IsFriendRes)(nil), // 1: pb.isFriendRes
}
var file_app_friend_rpc_pb_friend_proto_depIdxs = []int32{
	0, // 0: pb.friend.isFriend:input_type -> pb.isFriendReq
	1, // 1: pb.friend.isFriend:output_type -> pb.isFriendRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_friend_rpc_pb_friend_proto_init() }
func file_app_friend_rpc_pb_friend_proto_init() {
	if File_app_friend_rpc_pb_friend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_friend_rpc_pb_friend_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_friend_rpc_pb_friend_proto_goTypes,
		DependencyIndexes: file_app_friend_rpc_pb_friend_proto_depIdxs,
		MessageInfos:      file_app_friend_rpc_pb_friend_proto_msgTypes,
	}.Build()
	File_app_friend_rpc_pb_friend_proto = out.File
	file_app_friend_rpc_pb_friend_proto_rawDesc = nil
	file_app_friend_rpc_pb_friend_proto_goTypes = nil
	file_app_friend_rpc_pb_friend_proto_depIdxs = nil
}
