// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ChatWebsocketRequest struct {
	UserID string `form:"userId"` // 用户ID，用于身份识别
	Token  string `form:"token"`  // 用户token，用于验证
}

type ChatWebsocketResponse struct {
}
