// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	friendFieldNames          = builder.RawFieldNames(&Friend{})
	friendRows                = strings.Join(friendFieldNames, ",")
	friendRowsExpectAutoSet   = strings.Join(stringx.Remove(friendFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	friendRowsWithPlaceHolder = strings.Join(stringx.Remove(friendFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFriendIdPrefix           = "cache:friend:id:"
	cacheFriendFriendIdPrefix     = "cache:friend:friendId:"
	cacheFriendFriendshipIdPrefix = "cache:friend:friendshipId:"
)

type (
	friendModel interface {
		Insert(ctx context.Context, data *Friend) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Friend, error)
		FindOneByFriendId(ctx context.Context, friendId string) (*Friend, error)
		FindOneByFriendshipId(ctx context.Context, friendshipId string) (*Friend, error)
		Update(ctx context.Context, data *Friend) error
		Delete(ctx context.Context, id int64) error
	}

	defaultFriendModel struct {
		sqlc.CachedConn
		table string
	}

	Friend struct {
		Id             int64     `db:"id"`
		FriendId       string    `db:"friendId"`       // The friend id
		FriendshipId   string    `db:"friendshipId"`   // The friendship id
		SendUserId     string    `db:"sendUserId"`     // The send user id
		RevUserId      string    `db:"revUserId"`      // The receive user id
		SendUserNotice string    `db:"sendUserNotice"` // The send user notice
		RevUserNotice  string    `db:"revUserNotice"`  // The receive user notice
		CreateAt       time.Time `db:"create_at"`
		UpdateAt       time.Time `db:"update_at"`
		Source         string    `db:"source"`    // The friend source
		IsDeleted      string    `db:"isDeleted"` // The friend is deleted
	}
)

func newFriendModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFriendModel {
	return &defaultFriendModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`friend`",
	}
}

func (m *defaultFriendModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	friendFriendIdKey := fmt.Sprintf("%s%v", cacheFriendFriendIdPrefix, data.FriendId)
	friendFriendshipIdKey := fmt.Sprintf("%s%v", cacheFriendFriendshipIdPrefix, data.FriendshipId)
	friendIdKey := fmt.Sprintf("%s%v", cacheFriendIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, friendFriendIdKey, friendFriendshipIdKey, friendIdKey)
	return err
}

func (m *defaultFriendModel) FindOne(ctx context.Context, id int64) (*Friend, error) {
	friendIdKey := fmt.Sprintf("%s%v", cacheFriendIdPrefix, id)
	var resp Friend
	err := m.QueryRowCtx(ctx, &resp, friendIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendModel) FindOneByFriendId(ctx context.Context, friendId string) (*Friend, error) {
	friendFriendIdKey := fmt.Sprintf("%s%v", cacheFriendFriendIdPrefix, friendId)
	var resp Friend
	err := m.QueryRowIndexCtx(ctx, &resp, friendFriendIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `friendId` = ? limit 1", friendRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, friendId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendModel) FindOneByFriendshipId(ctx context.Context, friendshipId string) (*Friend, error) {
	friendFriendshipIdKey := fmt.Sprintf("%s%v", cacheFriendFriendshipIdPrefix, friendshipId)
	var resp Friend
	err := m.QueryRowIndexCtx(ctx, &resp, friendFriendshipIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `friendshipId` = ? limit 1", friendRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, friendshipId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendModel) Insert(ctx context.Context, data *Friend) (sql.Result, error) {
	friendFriendIdKey := fmt.Sprintf("%s%v", cacheFriendFriendIdPrefix, data.FriendId)
	friendFriendshipIdKey := fmt.Sprintf("%s%v", cacheFriendFriendshipIdPrefix, data.FriendshipId)
	friendIdKey := fmt.Sprintf("%s%v", cacheFriendIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, friendRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.FriendId, data.FriendshipId, data.SendUserId, data.RevUserId, data.SendUserNotice, data.RevUserNotice, data.Source, data.IsDeleted)
	}, friendFriendIdKey, friendFriendshipIdKey, friendIdKey)
	return ret, err
}

func (m *defaultFriendModel) Update(ctx context.Context, newData *Friend) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	friendFriendIdKey := fmt.Sprintf("%s%v", cacheFriendFriendIdPrefix, data.FriendId)
	friendFriendshipIdKey := fmt.Sprintf("%s%v", cacheFriendFriendshipIdPrefix, data.FriendshipId)
	friendIdKey := fmt.Sprintf("%s%v", cacheFriendIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, friendRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.FriendId, newData.FriendshipId, newData.SendUserId, newData.RevUserId, newData.SendUserNotice, newData.RevUserNotice, newData.Source, newData.IsDeleted, newData.Id)
	}, friendFriendIdKey, friendFriendshipIdKey, friendIdKey)
	return err
}

func (m *defaultFriendModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheFriendIdPrefix, primary)
}

func (m *defaultFriendModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFriendModel) tableName() string {
	return m.table
}
