// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	friendverifyFieldNames          = builder.RawFieldNames(&Friendverify{})
	friendverifyRows                = strings.Join(friendverifyFieldNames, ",")
	friendverifyRowsExpectAutoSet   = strings.Join(stringx.Remove(friendverifyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	friendverifyRowsWithPlaceHolder = strings.Join(stringx.Remove(friendverifyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFriendverifyIdPrefix       = "cache:friendverify:id:"
	cacheFriendverifyVerifyIdPrefix = "cache:friendverify:verifyId:"
)

type (
	friendverifyModel interface {
		Insert(ctx context.Context, data *Friendverify) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Friendverify, error)
		FindOneByVerifyId(ctx context.Context, verifyId string) (*Friendverify, error)
		Update(ctx context.Context, data *Friendverify) error
		Delete(ctx context.Context, id int64) error
		IsFriendVerify(ctx context.Context, userId1, userId2 string) (*Friendverify, error)
	}

	defaultFriendverifyModel struct {
		sqlc.CachedConn
		table string
	}

	Friendverify struct {
		Id         int64     `db:"id"`
		VerifyId   string    `db:"verifyId"`   // The verify id
		SendUserId string    `db:"sendUserId"` // The send user id
		RevUserId  string    `db:"revUserId"`  // The receive user id
		SendStatus string    `db:"sendStatus"` // The send user status, 发起方状态 0:未处理 1:已通过 2:已拒绝 3: 忽略 4:删除
		RevStatus  string    `db:"revStatus"`  // The receive user status, 接收方状态 0:未处理 1:已通过 2:已拒绝 3: 忽略 4:删除
		Createat   time.Time `db:"createat" gorm:"autoCreateTime"`
		Updateat   time.Time `db:"updateat" gorm:"autoUpdateTime"`
		Source     string    `db:"source"`  // The friend source
		Message    string    `db:"message"` // The friend verify message
		Version    int64     `db:"version"` // The friend verify version
	}
)

func newFriendverifyModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFriendverifyModel {
	return &defaultFriendverifyModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`friendverify`",
	}
}

func (m *defaultFriendverifyModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	friendverifyIdKey := fmt.Sprintf("%s%v", cacheFriendverifyIdPrefix, id)
	friendverifyVerifyIdKey := fmt.Sprintf("%s%v", cacheFriendverifyVerifyIdPrefix, data.VerifyId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, friendverifyIdKey, friendverifyVerifyIdKey)
	return err
}

func (m *defaultFriendverifyModel) FindOne(ctx context.Context, id int64) (*Friendverify, error) {
	friendverifyIdKey := fmt.Sprintf("%s%v", cacheFriendverifyIdPrefix, id)
	var resp Friendverify
	err := m.QueryRowCtx(ctx, &resp, friendverifyIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendverifyRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendverifyModel) FindOneByVerifyId(ctx context.Context, verifyId string) (*Friendverify, error) {
	friendverifyVerifyIdKey := fmt.Sprintf("%s%v", cacheFriendverifyVerifyIdPrefix, verifyId)
	var resp Friendverify
	err := m.QueryRowIndexCtx(ctx, &resp, friendverifyVerifyIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `verifyId` = ? limit 1", friendverifyRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, verifyId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendverifyModel) Insert(ctx context.Context, data *Friendverify) (sql.Result, error) {
	friendverifyIdKey := fmt.Sprintf("%s%v", cacheFriendverifyIdPrefix, data.Id)
	friendverifyVerifyIdKey := fmt.Sprintf("%s%v", cacheFriendverifyVerifyIdPrefix, data.VerifyId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, friendverifyRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.VerifyId, data.SendUserId, data.RevUserId, data.SendStatus, data.RevStatus, data.Createat, data.Updateat, data.Source, data.Message, data.Version)
	}, friendverifyIdKey, friendverifyVerifyIdKey)
	return ret, err
}

func (m *defaultFriendverifyModel) Update(ctx context.Context, newData *Friendverify) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	friendverifyIdKey := fmt.Sprintf("%s%v", cacheFriendverifyIdPrefix, data.Id)
	friendverifyVerifyIdKey := fmt.Sprintf("%s%v", cacheFriendverifyVerifyIdPrefix, data.VerifyId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, friendverifyRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.VerifyId, newData.SendUserId, newData.RevUserId, newData.SendStatus, newData.RevStatus, newData.Createat, newData.Updateat, newData.Source, newData.Message, newData.Version, newData.Id)
	}, friendverifyIdKey, friendverifyVerifyIdKey)
	return err
}

func (m *defaultFriendverifyModel) IsFriendVerify(ctx context.Context, userId1, userId2 string) (*Friendverify, error) {
	friendVerifyVerifyIdKey := fmt.Sprintf("%s%v", cacheFriendverifyIdPrefix, fmt.Sprintf("%s_%s", userId1, userId2))
	var resp Friendverify

	err := m.QueryRowIndexCtx(ctx, &resp, friendVerifyVerifyIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `sendUserId` = ? and `revUserId` = ? and `revStatus` = 0 or `sendUserId` = ? and `revUserId` = ? and `sendStatus` = 0 limit 1", friendverifyRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId1, userId2, userId2, userId1); err != nil {
			fmt.Println("==== err:", err)
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendverifyModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheFriendverifyIdPrefix, primary)
}

func (m *defaultFriendverifyModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendverifyRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFriendverifyModel) tableName() string {
	return m.table
}
