// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: friend.proto

package friend

import (
	"context"

	"beaver-server/app/friend/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	IsFriendReq = pb.IsFriendReq
	IsFriendRes = pb.IsFriendRes

	Friend interface {
		// 是否好友
		IsFriend(ctx context.Context, in *IsFriendReq, opts ...grpc.CallOption) (*IsFriendRes, error)
	}

	defaultFriend struct {
		cli zrpc.Client
	}
)

func NewFriend(cli zrpc.Client) Friend {
	return &defaultFriend{
		cli: cli,
	}
}

// 是否好友
func (m *defaultFriend) IsFriend(ctx context.Context, in *IsFriendReq, opts ...grpc.CallOption) (*IsFriendRes, error) {
	client := pb.NewFriendClient(m.cli.Conn())
	return client.IsFriend(ctx, in, opts...)
}
