// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"beaver-server/app/websocket/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// WebSocket连接
				Method:  http.MethodGet,
				Path:    "/api/chat/websocket",
				Handler: chatWebsocketHandler(serverCtx),
			},
		},
	)
}
