// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: friend.proto

package server

import (
	"context"

	"beaver-server/app/friend/rpc/internal/logic"
	"beaver-server/app/friend/rpc/internal/svc"
	"beaver-server/app/friend/rpc/pb"
)

type FriendServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFriendServer
}

func NewFriendServer(svcCtx *svc.ServiceContext) *FriendServer {
	return &FriendServer{
		svcCtx: svcCtx,
	}
}

// 是否好友
func (s *FriendServer) IsFriend(ctx context.Context, in *pb.IsFriendReq) (*pb.IsFriendRes, error) {
	l := logic.NewIsFriendLogic(ctx, s.svcCtx)
	return l.IsFriend(in)
}

// 是否验证中
func (s *FriendServer) IsFriendVerify(ctx context.Context, in *pb.IsFriendVerifyReq) (*pb.IsFriendVerifyRes, error) {
	l := logic.NewIsFriendVerifyLogic(ctx, s.svcCtx)
	return l.IsFriendVerify(in)
}
